import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/Header';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 const isLogin = cookies().has('authjs.csrf-token');
 return (
  <html lang="en">
   <body className={inter.className}>
    <Header isLogin={isLogin} />
    {children}
   </body>
  </html>
 );
}
